baseURL = 'https://marc-mm27.github.io/Hugo/'
languageCode = 'es-es'
title = 'Nombre de tu Sitio Web'

[params]
  # Subtítulo o texto que aparece bajo el título principal
  description = 'Una breve descripción o frase de bienvenida'
  
  # Imagen de fondo para el encabezado (debes guardarla en static/images/)
  featured_image = '/images/gohugo-default-sample-hero-image.jpg'
  
  # Color de fondo de la barra de navegación o cabecera
  background_color_class = 'bg-black'
